bosun-ai/swiftide

- Cargo.lock
- Cargo.toml
- crates/code_ops/Cargo.toml
- crates/indexing/Cargo.toml
- crates/infrastructure/Cargo.toml
- **chore: start cleaning up dependencies**
- **chore: remove more unused dependencies**
- **chore: remove more crates and update**
- **chore: clean up more crates**
- **chore: cargo update**
> chore: clean up left over deps after split

- swiftide/src/ingestion/ingestion_pipeline.rs
* Remove the clone from the node cache
* Run the node cache futures on tokio
* When flattening streams, do so unordered
> feat(ingestion_pipeline): concurrency improvements

- swiftide/src/ingestion/ingestion_pipeline.rs
- swiftide/src/traits.rs
- swiftide/src/transformers/chunk_code.rs
- swiftide/src/transformers/chunk_markdown.rs
- swiftide/src/transformers/metadata_qa_code.rs
- swiftide/src/transformers/metadata_qa_text.rs
- swiftide/src/transformers/openai_embed.rs
- swiftide/tests/ingestion_pipeline.rs
Optional configurable concurrency for transformers
> feat: configurable concurrency for transformers and chunkers

- README.md
I found some grammar issues and typos and fixed them. Great work, keep it up!
> Fixing some grammar typos on README.md

- swiftide/src/integrations/qdrant/mod.rs
- swiftide/src/integrations/redis/node_cache.rs
- swiftide/src/integrations/treesitter/splitter.rs
- swiftide/src/transformers/chunk_code.rs
- swiftide/src/transformers/chunk_markdown.rs
- swiftide/src/transformers/metadata_qa_code.rs
- swiftide/src/transformers/metadata_qa_text.rs
- **feat(integrations): clone and debug for integrations**
- **feat(transformers): builder and clone for chunk_code**
- **feat(transformers): builder for chunk_markdown**
- **feat(transformers): builder and clone for MetadataQACode**
- **feat(transformers): builder and clone for MetadataQAText**
> feat: even more builder consistency

- .github/workflows/coverage.yml
- .github/workflows/test.yml
- README.md
- swiftide/tests/ingestion_pipeline.rs
Post test coverage to Coveralls
Also enabled --all-features when running tests in ci, just to be sure
> chore(ci): code coverage reporting

- Cargo.lock
- examples/Cargo.toml
- examples/ingest_into_redis.rs
- swiftide/src/ingestion/ingestion_node.rs
- swiftide/src/integrations/redis/mod.rs
- swiftide/src/integrations/redis/node_cache.rs
- swiftide/src/integrations/redis/persist.rs
- swiftide/tests/ingestion_pipeline.rs
Enables redis to be used as storage as per #72
> feat(integrations)!: store stream results into redis

- Cargo.lock
- Cargo.toml
- benchmarks/Cargo.toml
- benchmarks/fileloader.rs
- benchmarks/local_pipeline.rs
- swiftide/src/loaders/file_loader.rs
- **feat(loaders): file loader performance improvements**
- **feat(benchmarks): add benchmark for the file loader**
- **feat(benchmarks): add benchmark for simple local pipeline**
> feat(loaders): file loader performance improvements, benchmarks and optional extension filtering

- Cargo.lock
- examples/Cargo.toml
- examples/scraping_ingest_to_markdown.rs
- swiftide/Cargo.toml
- swiftide/src/integrations/mod.rs
- swiftide/src/integrations/scraping/html_to_markdown_transformer.rs
- swiftide/src/integrations/scraping/loader.rs
- swiftide/src/integrations/scraping/mod.rs
- swiftide/src/lib.rs
- swiftide/src/persist/memory_storage.rs
- swiftide/src/persist/mod.rs
- **feat(loaders): add scraping using `spider`**
- **feat(integrations,transformers): add transformer for converting html to markdown**
- **feat(persist): in memory storage for testing, experimentation and debugging**
- **feat(examples,scraping): Add example scraping and ingesting a url**
> feat: crawl websites with spider and convert to md

- swiftide/src/ingestion/ingestion_pipeline.rs
- swiftide/src/persist/memory_storage.rs
- swiftide/src/traits.rs
- **feat(memory_storage): can be cloned safely preserving storage**
- **feat(transformers): allow for arbitrary closures as transformers and batchable transformers**
> feat: closures as transformers

- .github/workflows/coverage.yml
- Cargo.lock
- README.md
- examples/ingest_codebase.rs
- examples/ingest_markdown_lots_of_metadata.rs
- swiftide/Cargo.toml
- swiftide/src/integrations/qdrant/mod.rs
- swiftide/src/integrations/qdrant/persist.rs
- swiftide/tests/ingestion_pipeline.rs
- **fix(deps): update rust crate qdrant-client to v1.10.1**
- **fix(qdrant): upgrade to new qdrant with sensible defaults**
- **feat(qdrant): safe to clone with internal arc**
> fix(qdrant): upgrade and better defaults

- swiftide/Cargo.toml
Loosen up dependencies so swiftide is a bit more flexible to add to existing projects
> chore(swiftide): loosen up dependencies

- swiftide/src/integrations/qdrant/indexing_node.rs
- swiftide/src/integrations/qdrant/mod.rs
- swiftide/src/integrations/qdrant/persist.rs
> fix: Inability to store only some of `EmbeddedField`s

- Cargo.lock
- README.md
- examples/Cargo.toml
- examples/index_groq.rs
- swiftide/Cargo.toml
- swiftide/src/integrations/groq/config.rs
- swiftide/src/integrations/groq/mod.rs
- swiftide/src/integrations/groq/simple_prompt.rs
- swiftide/src/integrations/mod.rs
Adds simple prompt support for Groq by using async_openai. ~~Needs some double checks~~. Works great.
> feat(groq): Add SimplePrompt support for Groq

- Cargo.lock
- examples/Cargo.toml
- examples/index_ollama.rs
- swiftide-integrations/Cargo.toml
- swiftide-integrations/src/lib.rs
- swiftide-integrations/src/ollama/mod.rs
- swiftide-integrations/src/ollama/simple_prompt.rs
- swiftide/Cargo.toml
Implement ollama integration in the same style as the groq integration.
Ran the example in around 2 minutes on my MBP:
```
2024-08-02T13:49:57.353793Z  INFO indexing_pipeline.run: swiftide_indexing::pipeline: Starting indexing pipeline with 8 concurrency
2024-08-02T13:52:00.422713Z  WARN indexing_pipeline.run: swiftide_indexing::pipeline: Processed 20 nodes
Example results:
"Q1: What does Swiftide do?\nA1: It's a data indexing, processing and query library for Retrieval Augmented Generation (RAG).\n\nQ2: What language was Swiftide built in?\nA2: Rust.\n\nQ3: How fast is Swiftide?\nA3: It's blazingly fast.\n\nQ4: Why did the developers create Swiftide?\nA4: Because they were frustrated with other Python-based tooling that had performance, stability, and ease of use issues.\n\nQ5: What is …
```
> feat(integrations): add ollama support

- swiftide-core/src/indexing_traits.rs
- swiftide-core/src/query_traits.rs
- swiftide-indexing/src/loaders/file_loader.rs
When working with trait objects, some pipeline steps now allow for Box<dyn Trait> as well.
> feat: Implemtent traits T for Box<T> for indexing and query traits

- .github/dependabot.yml
Hopefully fix cargo not updating
> fix(ci): Update dependabot.yml via ui

- deny.toml
> chore: Updated ignored advisories in deny.toml

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide`: 0.14.1 -> 0.14.2 (✓ API compatible changes)
* `swiftide-core`: 0.14.1 -> 0.14.2 (✓ API compatible changes)
* `swiftide-indexing`: 0.14.1 -> 0.14.2 (✓ API compatible changes)
* `swiftide-macros`: 0.14.1 -> 0.14.2
* `swiftide-integrations`: 0.14.1 -> 0.14.2 (✓ API compatible changes)
* `swiftide-query`: 0.14.1 -> 0.14.2 (✓ API compatible changes)
<blockquote>
- [3924322](https://github.com/bosun-ai/swiftide/commit/39243224d739a76cf2b60204fc67819055b7bc6f) *(querying)*  Query pipeline is now properly send and sync when possible ([#425](https://github.com/bosun-ai/swiftide/pull/425))
- [52198f7](https://github.com/bosun-ai/swiftide/commit/52198f7fe76376a42c1fec8945bda4bf3e6971d4)  Improve local dev build speed …
> chore: release v0.14.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide`: 0.14.2 -> 0.14.3 (✓ API compatible changes)
* `swiftide-core`: 0.14.2 -> 0.14.3
* `swiftide-indexing`: 0.14.2 -> 0.14.3
* `swiftide-macros`: 0.14.2 -> 0.14.3
* `swiftide-integrations`: 0.14.2 -> 0.14.3 (✓ API compatible changes)
* `swiftide-query`: 0.14.2 -> 0.14.3
<blockquote>
- [1774b84](https://github.com/bosun-ai/swiftide/commit/1774b84f00a83fe69af4a2b6a6daf397d4d9b32d) *(integrations)*  Add PGVector support for indexing ([#392](https://github.com/bosun-ai/swiftide/pull/392))
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.14.2...0.14.3
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release v0.14.3

- .github/workflows/coverage.yml
- .github/workflows/test.yml
Sets the # jobs to 1. If issue persists, there's also some hacks to try to free up disk space.
> fix(ci): Reduce pipeline resource usage for build consistency

- Cargo.lock
- Cargo.toml
- swiftide-integrations/src/pgvector/pgv_table_types.rs
Add support for jina v2 code in fastembed.
Resolves #537
> feat(fastembed): Add support for jina v2 code

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide`: 0.16.2 -> 0.16.3 (✓ API compatible changes)
* `swiftide-agents`: 0.16.2 -> 0.16.3
* `swiftide-core`: 0.16.2 -> 0.16.3
* `swiftide-macros`: 0.16.2 -> 0.16.3
* `swiftide-indexing`: 0.16.2 -> 0.16.3
* `swiftide-integrations`: 0.16.2 -> 0.16.3 (✓ API compatible changes)
* `swiftide-query`: 0.16.2 -> 0.16.3
<blockquote>
- [b66bd79](https://github.com/bosun-ai/swiftide/commit/b66bd79070772d7e1bfe10a22531ccfd6501fc2a) *(fastembed)*  Add support for jina v2 code (#541)
````text
Add support for jina v2 code in fastembed.
````
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.16.2...0.16.3
</blockquote>
</p></details>
---
> chore: release v0.16.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide`: 0.17.2 -> 0.17.3 (✓ API compatible changes)
* `swiftide-agents`: 0.17.2 -> 0.17.3 (✓ API compatible changes)
* `swiftide-core`: 0.17.2 -> 0.17.3 (✓ API compatible changes)
* `swiftide-macros`: 0.17.2 -> 0.17.3
* `swiftide-indexing`: 0.17.2 -> 0.17.3 (✓ API compatible changes)
* `swiftide-integrations`: 0.17.2 -> 0.17.3 (✓ API compatible changes)
* `swiftide-query`: 0.17.2 -> 0.17.3 (✓ API compatible changes)
<blockquote>
- [8e22442](https://github.com/bosun-ai/swiftide/commit/8e2244241f16fff77591cf04f40725ad0b05ca81) *(integrations)*  Support Qdrant 1.13 (#571)
- [c5408a9](https://github.com/bosun-ai/swiftide/commit/c5408a96fbed6207022eb493da8d2cbb0fea7ca6) *(agents)*  Io::Error should always be a NonZeroExit error for …
> chore: release v0.17.3

- README.md
- swiftide-integrations/Cargo.toml
- swiftide-integrations/src/lib.rs
- swiftide-integrations/src/ollama/config.rs
- swiftide-integrations/src/open_router/chat_completion.rs
- swiftide-integrations/src/open_router/config.rs
- swiftide-integrations/src/open_router/mod.rs
- swiftide-integrations/src/open_router/simple_prompt.rs
- swiftide/Cargo.toml
Adds OpenRouter support. OpenRouter allows you to use any LLM via their own api (with a minor upsell).
> feat(integrations): OpenRouter support

- swiftide-agents/src/agent.rs
- swiftide-agents/src/hooks.rs
- swiftide-agents/src/test_utils.rs
- **feat(agents)!: Yield agent in hooks instead of context**
- **Clippy**
- **feat(agents): Add `on_start` hook for agents**
> feat(agents): Add `on_start` hook

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide`: 0.18.1
* `swiftide-agents`: 0.18.1
* `swiftide-core`: 0.18.1
* `swiftide-macros`: 0.18.1
* `swiftide-indexing`: 0.18.1
* `swiftide-integrations`: 0.18.1
* `swiftide-query`: 0.18.1
<blockquote>
- [78bf0e0](https://github.com/bosun-ai/swiftide/commit/78bf0e004049c852d4e32c0cd67725675b1250f9) *(agents)*  Add optional limit for agent iterations (#599)
- [592e5a2](https://github.com/bosun-ai/swiftide/commit/592e5a2ca4b0f09ba6a9b20cef105539cb7a7909) *(integrations)*  Support Azure openai via generics (#596)
</blockquote>
</p></details>
---
> chore: release v0.18.1

- swiftide-integrations/src/openai/chat_completion.rs
- swiftide-integrations/src/openai/mod.rs
Adds support reasoning models in agents and for chat completions.
> feat(integrations): Parallel tool calling in OpenAI is now configurable

- Cargo.lock
- swiftide-integrations/src/scraping/loader.rs
> fix(integrations): Scraper should stop when finished

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-agents/Cargo.toml
- swiftide-indexing/Cargo.toml
- swiftide-integrations/Cargo.toml
- swiftide-query/Cargo.toml
- swiftide/Cargo.toml
* `swiftide`: 0.19.0 -> 0.20.0 (✓ API compatible changes)
* `swiftide-agents`: 0.19.0 -> 0.20.0
* `swiftide-core`: 0.19.0 -> 0.20.0 (⚠ API breaking changes)
* `swiftide-macros`: 0.19.0 -> 0.20.0
* `swiftide-indexing`: 0.19.0 -> 0.20.0
* `swiftide-integrations`: 0.19.0 -> 0.20.0 (✓ API compatible changes)
* `swiftide-query`: 0.19.0 -> 0.20.0
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.39.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field …
```
> chore: release v0.20.0

- Cargo.toml
> fix: Correctly link to repository in Cargo.toml

- Cargo.lock
- Cargo.toml
- swiftide-integrations/Cargo.toml
- swiftide-integrations/src/treesitter/code_tree.rs
- swiftide-integrations/src/treesitter/outliner.rs
- swiftide-integrations/src/treesitter/supported_languages.rs
- **feat(tree-sitter): C and C++ support for splitter only**
- **Rename to C++**
> feat(treesitter): C and C++ support for splitter only

- swiftide-agents/src/default_context.rs
- swiftide-integrations/src/duckdb/mod.rs
- swiftide-integrations/src/duckdb/node_cache.rs
- swiftide-integrations/src/duckdb/persist.rs
- swiftide-integrations/src/duckdb/retrieve.rs
https://tokio.rs/tokio/tutorial/shared-state\#on-using-stdsyncmutex-and-tokiosyncmutex
> chore: use std::sync::Mutex instead of tokio mutex

- swiftide-indexing/src/loaders/file_loader.rs
The logging now logs appropriate detail about each file and node processed
- Skipped files are logged at TRACE level
- Configuration of the loader is logged at the start
- The necessary details to identify the loader (path) is included in the span fields
- You can now correlate a node id with a path
```
2025-03-17T00:34:18.965601Z DEBUG pipeline:file_loader{root=.}: swiftide_indexing::loaders::file_loader: Loading files extensions=Some(["rs"])
2025-03-17T00:34:18.968115Z TRACE pipeline:file_loader{root=.}:load{path=./Cargo.toml}: swiftide_indexing::loaders::file_loader: Skipping file with extension toml
2025-03-17T00:34:18.968153Z TRACE pipeline:file_loader{root=.}:load{path=./Cargo.lock}: swiftide_indexing::loaders::file_loader: Skipping file with extension lock …
```
> refactor: improve file loader logging

- swiftide-core/src/template.rs
- swiftide-core/src/test_utils.rs
- swiftide-indexing/src/transformers/embed.rs
- swiftide-integrations/src/pgvector/pgv_table_types.rs
- swiftide-integrations/src/pgvector/retrieve.rs
- **style: Clippy like it's 1.86**
- **More clipppy'ing**
> style: Clippy like it's 1.86

- swiftide-query/src/evaluators/ragas.rs
It's a bit unreadable without the formatting.
> chore: Pretty print RAGAS output

- Cargo.lock
- Cargo.toml
- swiftide-integrations/Cargo.toml
- swiftide-integrations/src/treesitter/code_tree.rs
- swiftide-integrations/src/treesitter/outliner.rs
- swiftide-integrations/src/treesitter/supported_languages.rs
Only for the splitter.
Closes #762.
> feat(treesitter): Add elixir support

- README.md
- examples/Cargo.toml
- examples/hello_agents.rs
- swiftide-integrations/Cargo.toml
- swiftide-integrations/src/gemini/config.rs
- swiftide-integrations/src/gemini/mod.rs
- swiftide-integrations/src/lib.rs
- swiftide/Cargo.toml
Google is now properly compatible with openai, so it works right away. Winning 🎉
> feat(integrations): Add support for Google Gemini

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-macros/Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide-core`: 0.27.1 -> 0.27.2 (✓ API compatible changes)
* `swiftide-agents`: 0.27.1 -> 0.27.2
* `swiftide-macros`: 0.27.1 -> 0.27.2
* `swiftide-indexing`: 0.27.1 -> 0.27.2
* `swiftide-integrations`: 0.27.1 -> 0.27.2 (✓ API compatible changes)
* `swiftide-query`: 0.27.1 -> 0.27.2
* `swiftide`: 0.27.1 -> 0.27.2 (✓ API compatible changes)
<blockquote>
- [66cd7e9](https://github.com/bosun-ai/swiftide/commit/66cd7e9349673a77d8cc79e6b5acab8d56078a42) *(qdrant)*  Add support for a filter in hybrid search ([#830](https://github.com/bosun-ai/swiftide/pull/830))
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.27.1...0.27.2
</blockquote>
</p></details>
---
This PR was generated with …
> chore: release v0.27.2

- .gitignore
- Cargo.lock
- swiftide-core/src/node.rs
- swiftide-indexing/Cargo.toml
- swiftide-indexing/src/pipeline.rs
- swiftide-indexing/src/transformers/chunk_markdown.rs
- swiftide-indexing/src/transformers/chunk_text.rs
- swiftide-integrations/src/duckdb/mod.rs
- swiftide-integrations/src/redb/mod.rs
- swiftide-integrations/src/redis/mod.rs
- swiftide-integrations/src/scraping/html_to_markdown_transformer.rs
- swiftide-integrations/src/treesitter/chunk_code.rs
- swiftide/Cargo.toml
- swiftide/tests/deferred_caching.rs
> fix(pipeline): Cache nodes after they've been successfully ran

- Cargo.lock
- Cargo.toml
- benchmarks/fileloader.rs
- swiftide-agents/src/agent.rs
- swiftide-indexing/src/loaders/file_loader.rs
- swiftide-integrations/src/openai/chat_completion.rs
- swiftide-integrations/src/openai/embed.rs
- swiftide-integrations/src/openai/simple_prompt.rs
- swiftide/src/lib.rs
- **chore(deps): Cargo update everything**
- **Clippy**
> chore(deps): Up all crates

- Cargo.lock
- examples/Cargo.toml
- examples/tasks.rs
- swiftide-agents/src/agent.rs
- swiftide-agents/src/lib.rs
- swiftide-agents/src/state.rs
- swiftide-agents/src/tasks/closures.rs
- swiftide-agents/src/tasks/errors.rs
- swiftide-agents/src/tasks/impls.rs
- swiftide-agents/src/tasks/mod.rs
- swiftide-agents/src/tasks/node.rs
- swiftide-agents/src/tasks/task.rs
- swiftide-agents/src/tasks/transition.rs
- swiftide-agents/src/test_utils.rs
- swiftide-agents/src/tools/control.rs
- swiftide-core/src/agent_traits.rs
- swiftide-core/src/chat_completion/errors.rs
- swiftide-core/src/chat_completion/tools.rs
- swiftide-macros/src/tool/mod.rs
- swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_args.snap
- swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_generics.snap
- swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_lifetime.snap
- swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_option.snap
- swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_multiple_args.snap
- swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg.snap
- swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg_option.snap
> feat(agents): Multi agent setup with graph-like Tasks

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide-core`: 0.30.0 -> 0.30.1 (✓ API compatible changes)
* `swiftide-macros`: 0.30.0 -> 0.30.1
* `swiftide-indexing`: 0.30.0 -> 0.30.1
* `swiftide-agents`: 0.30.0 -> 0.30.1 (✓ API compatible changes)
* `swiftide-integrations`: 0.30.0 -> 0.30.1 (✓ API compatible changes)
* `swiftide-query`: 0.30.0 -> 0.30.1 (✓ API compatible changes)
* `swiftide`: 0.30.0 -> 0.30.1 (✓ API compatible changes)
<blockquote>
- [0114573](https://github.com/bosun-ai/swiftide/commit/011457367b7bfdc207f1f6d9ebfcbf2a2de4ac58) *(agents)*  Explicitly handle out of bounds and empty edge cases for message history
- [1005ac2](https://github.com/bosun-ai/swiftide/commit/1005ac219e2078c6ee12b050a7e73d48ef7f46a5) *(core)*  Export tokenizer traits from the root …
> chore: release v0.30.1

- Cargo.lock
- examples/Cargo.toml
- examples/index_codebase.rs
- examples/structured_prompt.rs
- swiftide-core/Cargo.toml
- swiftide-core/src/indexing_traits.rs
- swiftide-integrations/Cargo.toml
- swiftide-integrations/src/openai/mod.rs
- swiftide-integrations/src/openai/structured_prompt.rs
With the indexing now being generic, we can do cool stuff like using structured prompts for classification, graphs, etc.
> feat(integrations/openai, core): Add `StructuredPrompt` and implement for OpenAI

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- swiftide-query/Cargo.toml
* `swiftide-core`: 0.31.1 -> 0.31.2
* `swiftide-macros`: 0.31.1 -> 0.31.2
* `swiftide-indexing`: 0.31.1 -> 0.31.2
* `swiftide-agents`: 0.31.1 -> 0.31.2 (✓ API compatible changes)
* `swiftide-integrations`: 0.31.1 -> 0.31.2 (✓ API compatible changes)
* `swiftide-langfuse`: 0.31.1 -> 0.31.2 (✓ API compatible changes)
* `swiftide-query`: 0.31.1 -> 0.31.2
* `swiftide`: 0.31.1 -> 0.31.2 (✓ API compatible changes)
<blockquote>
- [f35c9b5](https://github.com/bosun-ai/swiftide/commit/f35c9b507e11f76ff7e78de35843b3310a25f3db) *(agents)*  Add builder lite methods to SystemPrompt
- [9f533f5](https://github.com/bosun-ai/swiftide/commit/9f533f57b2c7ed4ac1988f9e3567cda42f64b824) *(agents)*  Add helpers to retrieve or mutate the system prompt
- …
> chore: release v0.31.2
