README.md
examples/ingest_codebase.rs
swiftide/src/ingestion/ingestion_pipeline.rs
swiftide/src/integrations/qdrant/persist.rs
swiftide/src/traits.rs
swiftide/tests/ingestion_pipeline.rs

Enables adding multiple storage backends to the ingestion pipeline. I've also renamed the `Storage` trait to `Persist` to better reflect its purpose.
This is a breaking change.
- **feat(ingestion_pipeline): support multiple streamed storage backends**
- **refactor(traits): rename storage trait to Persist**
- **docs: update documentation**

feat(ingestion_pipeline)!: support chained storage backends

---

swiftide/src/integrations/openai/mod.rs
swiftide/src/integrations/qdrant/mod.rs

* Strips option where applicable
* vector size is always u64
* Always use Into where possible

feat(integrations): qdrant and openai builder should be consistent

---

swiftide/src/ingestion/ingestion_pipeline.rs

Closes #73 and closes #64
Introduces various methods for stream inspection and skipping errors at a desired stage in the stream.

feat(ingestion_pipeline): optional error filtering and logging

---

swiftide/src/ingestion/ingestion_pipeline.rs
swiftide/src/traits.rs

Currency does did not work as expected. When spawning via `Tokio::spawn` the future would be polled directly, and any concurrency setting would not be respected. Because it had to be removed, improved tracing for each step as well.

fix(ingestion_pipeline): concurrency does not work when spawned

---

examples/Cargo.toml
examples/ingest_markdown_lots_of_metadata.rs
swiftide/src/ingestion/ingestion_node.rs
swiftide/src/integrations/openai/simple_prompt.rs
swiftide/src/traits.rs
swiftide/src/transformers/metadata_keywords.rs
swiftide/src/transformers/metadata_qa_code.rs
swiftide/src/transformers/metadata_qa_text.rs
swiftide/src/transformers/metadata_summary.rs
swiftide/src/transformers/metadata_title.rs
swiftide/src/transformers/mod.rs

Closes #68 
Need to double tap on the examples before merging.
- **feat(ingestion_node): add constructor with defaults**
- **feat(traits): add automock for simpleprompt**
- **feat(transformers): add transformers for title, summary and keywords**
- **feat(examples): example for markdown with all metadata**
- **feat: add example**

feat: more transformers

---

Cargo.lock
swiftide/Cargo.toml
swiftide/src/ingestion/ingestion_pipeline.rs
swiftide/src/ingestion/ingestion_stream.rs
swiftide/src/integrations/qdrant/persist.rs
swiftide/src/integrations/redis/persist.rs
swiftide/src/loaders/file_loader.rs
swiftide/src/transformers/chunk_code.rs
swiftide/src/transformers/chunk_markdown.rs
swiftide/src/transformers/embed.rs

Improves stream ergonomics by providing convenient helpers and `Into` for streams, vectors and iterators that match the internal type.
This means that in many cases, trait implementers can simply call `.into()` instead of manually constructing a stream. In the case it's an iterator, they can now use `IngestionStream::iter(<IntoIterator>)` instead.

feat(ingestion_stream): improved stream developer experience

---

swiftide/src/ingestion/ingestion_pipeline.rs
swiftide/src/ingestion/ingestion_stream.rs
swiftide/src/transformers/embed.rs

- **refactor(ingestion_pipeline): log_all combines other log helpers**
- **feat(ingestion_stream): implement into for Result<Vec<IngestionNode>>**
- **fix(embed): panic if number of embeddings and node are equal**

fix(embed): panic in rare cases num embeddings != num nodes

---

swiftide/src/ingestion/ingestion_pipeline.rs
swiftide/src/ingestion/ingestion_stream.rs

Closes #67 
Introduces several related major features:
* Stream splitting and merging; extremely useful. Streams can be split multiple times. The provided helper only merges two streams, but it's perfectly possible to merge as many as desired. Default merge alternates between the streams so that it doesn't break concurrency settings.
* mpsc::tokio::Receiver can now be converted into an IngestionStream
* ... which makes a IngestionPipeline::from_stream really interesting. You can hook up what you already have to a pipeline, connecting streams to streams to streams of streams :tada:

feat(ingestion_pipeline): stream splitting and merging + build from stream

---

benchmarks/local_pipeline.rs
examples/aws_bedrock.rs
examples/ingest_markdown_lots_of_metadata.rs
examples/scraping_ingest_to_markdown.rs
swiftide/src/integrations/openai/mod.rs
swiftide/src/transformers/chunk_markdown.rs

For reasons unknown the markdown chunker was not skipping chunks smaller than the given min. 
Improved test coverage while I was at it.

fix(transformers)!: markdown chunker not skipping small chunks

---

Cargo.lock
Cargo.toml
swiftide/Cargo.toml
swiftide/src/indexing/node.rs
swiftide/src/indexing/pipeline.rs
swiftide/src/integrations/aws_bedrock/simple_prompt.rs
swiftide/src/integrations/openai/simple_prompt.rs
swiftide/src/integrations/qdrant/indexing_node.rs
swiftide/src/integrations/qdrant/mod.rs
swiftide/src/lib.rs
swiftide/src/prompt.rs
swiftide/src/traits.rs
swiftide/src/transformers/embed.rs
swiftide/src/transformers/metadata_keywords.rs
swiftide/src/transformers/metadata_qa_code.rs
swiftide/src/transformers/metadata_qa_text.rs
swiftide/src/transformers/metadata_summary.rs
swiftide/src/transformers/metadata_title.rs
swiftide/src/transformers/prompts/metadata_keywords.prompt.md
swiftide/src/transformers/prompts/metadata_qa_code.prompt.md
swiftide/src/transformers/prompts/metadata_qa_text.prompt.md
swiftide/src/transformers/prompts/metadata_summary.prompt.md
swiftide/src/transformers/prompts/metadata_title.prompt.md
swiftide/src/transformers/snapshots/swiftide__transformers__metadata_keywords__test__template.snap
swiftide/src/transformers/snapshots/swiftide__transformers__metadata_qa_code__test__template.snap
swiftide/src/transformers/snapshots/swiftide__transformers__metadata_qa_text__test__template.snap
swiftide/src/transformers/snapshots/swiftide__transformers__metadata_summary__test__template.snap
swiftide/src/transformers/snapshots/swiftide__transformers__metadata_title__test__template.snap
swiftide/tests/indexing_pipeline.rs

Adds Prompts as first class citizens. This is a breaking change as SimplePrompt with just a a `&str` is no longer allowed.
This introduces `Prompt` and `PromptTemplate`. A template uses jinja style templating build on tera. Templates can be converted into prompts, and have context added. A prompt is then send to something that prompts, i.e. openai or bedrock.
Additional prompts can be added either compiled or as one-offs. Additionally, it's perfectly fine to prompt with just a string as well, just provide an `.into()`.
For future development, some LLMs really benefit from system prompts, which this would enable. For the query pipeline we can also take a much more structured approach with composed templates and conditionals.

feat(prompts): add prompts as first class citizens

---

swiftide/Cargo.toml
swiftide/src/prompt.rs

- **add prompts to crate**
- **load prompts via cargo manifest dir**

fix(prompts): include default prompts in crate

---

README.md
swiftide/src/integrations/treesitter/code_tree.rs
swiftide/src/integrations/treesitter/mod.rs
swiftide/src/integrations/treesitter/queries.rs
swiftide/src/transformers/metadata_refs_defs_code.rs
swiftide/src/transformers/mod.rs

Extract references and definitions from code with tree-sitter and add them as metadata to nodes.
Closes #165

feat(transformers): References and definitions from code

---

Cargo.lock
README.md
examples/Cargo.toml
examples/hybrid_search.rs
swiftide-core/src/indexing_traits.rs
swiftide-core/src/node.rs
swiftide-core/src/type_aliases.rs
swiftide-indexing/src/pipeline.rs
swiftide-indexing/src/transformers/mod.rs
swiftide-indexing/src/transformers/sparse_embed.rs
swiftide-integrations/src/fastembed/embedding_model.rs
swiftide-integrations/src/fastembed/mod.rs
swiftide-integrations/src/fastembed/sparse_embedding_model.rs
swiftide-integrations/src/qdrant/indexing_node.rs
swiftide-integrations/src/qdrant/mod.rs
swiftide-integrations/src/qdrant/persist.rs
swiftide-test-utils/src/test_utils.rs
swiftide/tests/indexing_pipeline.rs
swiftide/tests/sparse_embeddings.rs
swiftide/tests/sparse_embeddings_and_hybrid_search.rs

Adds Sparse vector support to the indexing pipeline, enabling hybrid search for vector databases. The design should work for any form of Sparse embedding, and works with existing embedding modes and multiple named vectors. Additionally, added `try_default_sparse` to FastEmbed, using Splade, so it's fully usuable.
Hybrid search in the query pipeline coming soon.

feat(indexing): Sparse vector support with Splade and Qdrant

---

swiftide-core/src/query.rs
swiftide-query/src/query/pipeline.rs

- **fix(query): After retrieval current transormation should be empty**
- **feat(query): Add concurrency on query pipeline and add query_all**

feat: Query pipeline improvements (no squash)

---

Cargo.lock
README.md
deny.toml
examples/Cargo.toml
examples/fluvio.rs
swiftide-integrations/Cargo.toml
swiftide-integrations/src/fluvio/loader.rs
swiftide-integrations/src/fluvio/mod.rs
swiftide-integrations/src/lib.rs
swiftide/Cargo.toml

Adds Fluvio as a loader support, enabling Swiftide indexing streams to process messages from a Fluvio topic.
Closes #240

feat(integrations): Add fluvio as loader support

---

.github/workflows/bench.yml
.github/workflows/coverage.yml
.github/workflows/release.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
benchmarks/Cargo.toml
deny.toml
examples/Cargo.toml
examples/lancedb.rs
swiftide-core/Cargo.toml
swiftide-core/src/indexing_stream.rs
swiftide-core/src/node.rs
swiftide-core/src/query.rs
swiftide-integrations/Cargo.toml
swiftide-integrations/src/lancedb/connection_pool.rs
swiftide-integrations/src/lancedb/mod.rs
swiftide-integrations/src/lancedb/persist.rs
swiftide-integrations/src/lancedb/retrieve.rs
swiftide-integrations/src/lib.rs
swiftide/Cargo.toml
swiftide/tests/lancedb.rs

Add LanceDB support for indexing and querying. LanceDB separates compute from storage, where storage can be local or hosted elsewhere.
Closes #239

feat: LanceDB support

---

Cargo.toml

Integrations are messy and pull a lot in. A potential solution is to disable default features, only add what is actually required, and put the responsibility at users if they need anything specific. Feature unification should then take care of the rest.

chore: Default features cleanup

---

README.md
examples/hybrid_search.rs
swiftide-core/src/query.rs
swiftide-core/src/search_strategies.rs
swiftide-integrations/src/qdrant/retrieve.rs
swiftide-query/src/query/pipeline.rs
swiftide-query/src/query_transformers/mod.rs
swiftide-query/src/query_transformers/sparse_embed.rs
swiftide/tests/query_pipeline.rs

Implement hybrid search for qdrant with their new Fusion search. Example in /examples includes an indexing and query pipeline, included the example answer as well.

feat(query): hybrid search for qdrant in query pipeline

---

README.md

I suppose this should be 09-02.

docs(README): Fix date

---

benchmarks/Cargo.toml
swiftide-core/src/query_traits.rs
swiftide-integrations/src/qdrant/indexing_node.rs
swiftide-integrations/src/redis/persist.rs

Fixing id generation properly as per #272, will be merged in together.
- **Clippy**
- **fix(qdrant)!: Default hasher changed in Rust 1.81**

fix!: Rust 1.81 support

---

Cargo.lock
Cargo.toml
swiftide-core/Cargo.toml
swiftide-core/src/node.rs
swiftide-integrations/src/fluvio/loader.rs
swiftide-integrations/src/lancedb/mod.rs
swiftide-integrations/src/lancedb/persist.rs
swiftide-integrations/src/qdrant/indexing_node.rs
swiftide-integrations/src/redis/mod.rs
swiftide-integrations/src/redis/node_cache.rs
swiftide-integrations/src/redis/persist.rs

Use UUIDv3 to generate node ids for storage and cache. This is more reliable than the previous u64 hashing, with less chance for collision. Additionally, the previous hash algorithm changes over Rust releases and should not be used.
Closes #272 and needed for proper Rust 1.81 support as in #275 
BREAKING CHANGE: All generated ids are now UUIDs, meaning all persisted data needs to be purged or manually updated, as default upserts will fail. There is no backwards compatibility.

feat(indexing)!: Use UUIDv3 for indexing node ids

---

Cargo.lock
swiftide-integrations/Cargo.toml
swiftide-integrations/src/ollama/embed.rs
swiftide-integrations/src/ollama/mod.rs

Update to the most recent ollama-rs, which exposes the batch embedding API Ollama exposes (https://github.com/pepperoni21/ollama-rs/pull/61). This allows the Ollama struct in Swiftide to implement `EmbeddingModel`. 
Use the same pattern that the OpenAI struct uses to manage separate embedding and prompt models.

feat(integrations): Add ollama embeddings support

---

.github/workflows/coverage.yml
Cargo.toml
swiftide-core/src/lib.rs
swiftide-core/src/query.rs
swiftide-core/src/query_evaluation.rs
swiftide-core/src/query_traits.rs
swiftide-core/src/type_aliases.rs
swiftide-indexing/src/pipeline.rs
swiftide-macros/src/lib.rs
swiftide-query/src/query/pipeline.rs

Fix test coverage in CI. Simplified the trait bounds on the query pipeline for now to make it all work and fit together, and added more tests to assert boxed versions of trait objects work in tests.

fix(ci): Use llm-cov preview via nightly and improve test coverage

---

swiftide-core/src/indexing_stream.rs
swiftide-core/src/node.rs
swiftide-indexing/src/transformers/embed.rs
swiftide-indexing/src/transformers/sparse_embed.rs
swiftide-integrations/src/openai/embed.rs

- **fix(indexing): Limit logged chunk to max 100 chars**
- **fix: Embed transformers must correctly propagate errors**

fix: Bad embed error propagation

---

swiftide-indexing/src/pipeline.rs

Futures that do not yield were not run in parallel properly. With this futures are spawned on a tokio worker thread by default.
When embedding (fastembed) and storing a 85k row dataset, there's a ~1.35x performance improvement:
~~Need to do one more test with IO bound futures as well. Pretty huge, not that it was slow.~~
With IO bound openai it's 1.5x.

feat: Major performance improvements

---

.github/workflows/test.yml
Cargo.lock
swiftide-core/src/indexing_traits.rs
swiftide-core/src/lib.rs
swiftide-core/src/metadata.rs
swiftide-core/src/node.rs
swiftide-core/src/query.rs
swiftide-core/src/query_evaluation.rs
swiftide-core/src/query_traits.rs
swiftide-core/src/util.rs
swiftide-indexing/src/pipeline.rs
swiftide-integrations/src/openai/simple_prompt.rs
swiftide-integrations/src/qdrant/persist.rs
swiftide-query/src/answers/simple.rs
swiftide-query/src/evaluators/ragas.rs
swiftide-query/src/query/pipeline.rs
swiftide-query/src/query_transformers/embed.rs
swiftide-query/src/query_transformers/generate_subquestions.rs
swiftide-query/src/query_transformers/sparse_embed.rs
swiftide-query/src/response_transformers/summary.rs
swiftide-test-utils/src/test_utils.rs

Cleans up and by default truncates the verbosity of any long strings to 100 chars. Every step now has an info log with the inferred name of the step as well. 
Let's add more verbosity when it's needed, there is still a good case to be made when evaluating pipelines, but the default does not scale.

feat: debugging verbosity improvements

---

swiftide-core/src/node.rs
swiftide-core/src/prompt.rs
swiftide-core/src/query_evaluation.rs
swiftide-indexing/src/pipeline.rs
swiftide-indexing/src/transformers/mod.rs
swiftide-integrations/src/groq/mod.rs
swiftide-integrations/src/qdrant/mod.rs
swiftide-integrations/src/treesitter/metadata_refs_defs_code.rs
swiftide-query/src/evaluators/mod.rs
swiftide/src/lib.rs

Running `cargo doc --all-features` resulted in a lot of warnings. We should probably add this to the CI/CD pipeline to prevent it from degrading again.

docs: fix broken documentation links and other cargo doc warnings

---

swiftide-integrations/src/treesitter/code_tree.rs
swiftide-integrations/src/treesitter/metadata_refs_defs_code.rs
swiftide-integrations/src/treesitter/queries.rs

As learned from #309, test coverage for the refs defs transformer was not great. There _are_ more tests in code_tree. Turns out, with the latest treesitter update, javascript broke as it was the only language not covered at all.

fix(tree-sitter): Fix javascript and improve tests

---

.github/workflows/discord.yml
.github/workflows/release.yml

Should be fixed as the default github token prevents other workflows to trigger in the release workflow.

fix(ci): Discord anounce

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.12.2 -> 0.12.3 (✓ API compatible changes)
* `swiftide-core`: 0.12.2 -> 0.12.3 (✓ API compatible changes)
* `swiftide-indexing`: 0.12.2 -> 0.12.3 (✓ API compatible changes)
* `swiftide-macros`: 0.12.2 -> 0.12.3
* `swiftide-integrations`: 0.12.2 -> 0.12.3 (✓ API compatible changes)
* `swiftide-query`: 0.12.2 -> 0.12.3 (✓ API compatible changes)
<blockquote>
- [da5df22](https://github.com/bosun-ai/swiftide/commit/da5df2230da81e9fe1e6ab74150511cbe1e3d769) *(tree-sitter)*  Implement Serialize and Deserialize for SupportedLanguages ([#314](https://github.com/bosun-ai/swiftide/pull/314))
- [a756148](https://github.com/bosun-ai/swiftide/commit/a756148f85faa15b1a79db8ec8106f0e15e4d6a2) *(tree-sitter)*  Fix javascript and …

chore: release v0.12.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.12.3 -> 0.13.0 (✓ API compatible changes)
* `swiftide-core`: 0.12.3 -> 0.13.0 (✓ API compatible changes)
* `swiftide-indexing`: 0.12.3 -> 0.13.0 (⚠️ API breaking changes)
* `swiftide-macros`: 0.12.3 -> 0.13.0
* `swiftide-integrations`: 0.12.3 -> 0.13.0 (⚠️ API breaking changes)
* `swiftide-query`: 0.12.3 -> 0.13.0 (✓ API compatible changes)
```
--- failure method_parameter_count_changed: pub method parameter count changed ---
Description:
A publicly-visible method now takes a different number of parameters.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#fn-change-arity
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.35.0/src/lints/method_parameter_count_changed.ron
Failed in:
swiftide_indexing::Pipeline::then_in_batch now takes 2 parameters …
```

chore: release v0.13.0

---

Cargo.lock
Cargo.toml
benchmarks/Cargo.toml
benchmarks/node_cache_comparison.rs
swiftide-core/Cargo.toml
swiftide-core/src/indexing_traits.rs
swiftide-integrations/Cargo.toml
swiftide-integrations/src/lib.rs
swiftide-integrations/src/redb/mod.rs
swiftide-integrations/src/redb/node_cache.rs
swiftide-integrations/src/redis/node_cache.rs
swiftide/Cargo.toml

Adds support for Redb as an embeddable node cache, allowing full local app development without needing external services.

feat(indexing): Support Redb as embedable nodecache

---

swiftide-core/src/indexing_traits.rs
swiftide-core/src/query_traits.rs
swiftide-indexing/src/loaders/file_loader.rs
swiftide-indexing/src/transformers/chunk_markdown.rs
swiftide-indexing/src/transformers/chunk_text.rs
swiftide-indexing/src/transformers/embed.rs
swiftide-indexing/src/transformers/sparse_embed.rs
swiftide-integrations/src/scraping/loader.rs

For instance, if you have a `Box<dyn SimplePrompt>`, you can now clone into an owned copy and more effectively use the available generics. This also works for borrowed trait objects.

feat(core): Add support for cloning all trait objects

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.13.1 -> 0.13.2 (✓ API compatible changes)
* `swiftide-core`: 0.13.1 -> 0.13.2 (✓ API compatible changes)
* `swiftide-indexing`: 0.13.1 -> 0.13.2 (✓ API compatible changes)
* `swiftide-macros`: 0.13.1 -> 0.13.2
* `swiftide-integrations`: 0.13.1 -> 0.13.2 (✓ API compatible changes)
* `swiftide-query`: 0.13.1 -> 0.13.2 (✓ API compatible changes)
<blockquote>
- [4b13aa7](https://github.com/bosun-ai/swiftide/commit/4b13aa7d76dfc7270870682e2f757f066a99ba4e) *(core)*  Add support for cloning all trait objects ([#355](https://github.com/bosun-ai/swiftide/pull/355))
````text
For instance, if you have a `Box<dyn SimplePrompt>`, you can now clone
into an owned copy and more effectively use the available generics. This
also works …
```

chore: release v0.13.2

---

swiftide-integrations/src/treesitter/compress_code_outline.rs

Regex compilation is not cheap, use a static with a oncelock instead.

fix(tree-sitter): Compile regex only once

---

.github/workflows/coverage.yml
.github/workflows/test.yml
Cargo.toml

Ensure swiftide\* crates are always included. Additionally, these are the default members, excluding examples and benches.

chore: Improve workspace configuration

---

swiftide-core/src/node.rs
swiftide-indexing/src/loaders/file_loader.rs
swiftide-indexing/src/persist/memory_storage.rs
swiftide-indexing/src/pipeline.rs
swiftide-indexing/src/transformers/chunk_markdown.rs
swiftide-indexing/src/transformers/chunk_text.rs
swiftide-indexing/src/transformers/embed.rs
swiftide-indexing/src/transformers/sparse_embed.rs
swiftide-integrations/src/qdrant/indexing_node.rs
swiftide-integrations/src/qdrant/mod.rs
swiftide-integrations/src/redis/node_cache.rs
swiftide-integrations/src/redis/persist.rs
swiftide-integrations/src/scraping/html_to_markdown_transformer.rs
swiftide-integrations/src/scraping/loader.rs
swiftide-integrations/src/treesitter/chunk_code.rs
swiftide-test-utils/src/test_utils.rs

As @shamb0 pointed out in #392, there is a potential issue where Node ids are get cached before chunking or other transformations, breaking upserts and potentially resulting in data loss.
BREAKING CHANGE: This PR reworks Nodes with a builder API and a private id. Hence, manually creating nodes no longer works. In the future, all the fields are likely to follow the same pattern, so that we can decouple the inner fields from the Node's implementation.

fix(indexing)!: Node ID no longer memoized

---

.github/workflows/coverage.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
README.md
deny.toml
examples/Cargo.toml
examples/mistralrs.rs
swiftide-integrations/Cargo.toml
swiftide-integrations/src/lib.rs
swiftide-integrations/src/mistralrs/mod.rs
swiftide-integrations/src/mistralrs/simple_prompt.rs
swiftide/Cargo.toml
swiftide/tests/lancedb.rs

Adds supporting for using inline popular hugging face models, in the same process, via `mistral-rs`. Currently only text models are supported. Experimental feature.
Related to #356 and resolves #66

feat(integrations): Support in process hugging face models via mistralrs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.13.4 -> 0.14.0 (✓ API compatible changes)
* `swiftide-core`: 0.13.4 -> 0.14.0 (⚠️ API breaking changes)
* `swiftide-indexing`: 0.13.4 -> 0.14.0 (✓ API compatible changes)
* `swiftide-macros`: 0.13.4 -> 0.14.0
* `swiftide-integrations`: 0.13.4 -> 0.14.0 (✓ API compatible changes)
* `swiftide-query`: 0.13.4 -> 0.14.0 (✓ API compatible changes)
```
--- failure inherent_method_missing: pub method removed or renamed ---
Description:
A publicly-visible method or associated fn is no longer available under its prior name. It may have been renamed or removed entirely.
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.36.0/src/lints/inherent_method_missing.ron
Failed in:
Node::update_id, previously …
```

chore: release v0.14.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

Revert the 0.14 release as `mistralrs` is unpublished and unfortunately cannot be released.

fix: Revert 0.14 release as mistralrs is unpublished

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

- **Revert "fix: Revert 0.14 release as mistralrs is unpublished (#417)"**
- **Fix changelog**

chore: Re-release 0.14 without mistralrs

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.14.0 -> 0.14.1 (✓ API compatible changes)
* `swiftide-core`: 0.14.0 -> 0.14.1
* `swiftide-indexing`: 0.14.0 -> 0.14.1 (✓ API compatible changes)
* `swiftide-macros`: 0.14.0 -> 0.14.1
* `swiftide-integrations`: 0.14.0 -> 0.14.1
* `swiftide-query`: 0.14.0 -> 0.14.1
<blockquote>
- [5bbcd55](https://github.com/bosun-ai/swiftide/commit/5bbcd55de65d73d7908e91c96f120928edb6b388)  Revert 0.14 release as mistralrs is unpublished ([#417](https://github.com/bosun-ai/swiftide/pull/417))
````text
Revert the 0.14 release as `mistralrs` is unpublished and unfortunately
cannot be released.
````
- [07c2661](https://github.com/bosun-ai/swiftide/commit/07c2661b7a7cdf75cdba12fab0ca91866793f727)  Re-release 0.14 without mistralrs …

chore: release v0.14.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.14.3 -> 0.14.4 (✓ API compatible changes)
* `swiftide-agents`: 0.14.3 -> 0.14.4
* `swiftide-core`: 0.14.3 -> 0.14.4 (✓ API compatible changes)
* `swiftide-macros`: 0.14.3 -> 0.14.4
* `swiftide-integrations`: 0.14.3 -> 0.14.4 (✓ API compatible changes)
* `swiftide-indexing`: 0.14.3 -> 0.14.4 (✓ API compatible changes)
* `swiftide-query`: 0.14.3 -> 0.14.4 (✓ API compatible changes)
<blockquote>
- [7211559](https://github.com/bosun-ai/swiftide/commit/7211559936d8b5e16a3b42f9c90b42a39426be8a) *(agents)*  **EXPERIMENTAL** Agents in Swiftide (#463)
````text
Agents are coming to Swiftide! We are still ironing out all the kinks,
while we make it ready for a proper release. You can already experiment
with agents, see the …
```

chore: release v0.14.4

---

swiftide-agents/src/tools/local_executor.rs
swiftide-core/src/agent_traits.rs

Better describes what is going on. I.e. `rg` exits with 1 if nothing is
found, tests generally do the same if they fail.

feat(agents): Rename `CommandError::FailedWithOutput` to `CommandError::NonZeroExit`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.14.4 -> 0.15.0 (⚠️ API breaking changes)
* `swiftide-agents`: 0.14.4 -> 0.15.0 (✓ API compatible changes)
* `swiftide-core`: 0.14.4 -> 0.15.0 (⚠️ API breaking changes)
* `swiftide-macros`: 0.14.4 -> 0.15.0
* `swiftide-integrations`: 0.14.4 -> 0.15.0 (✓ API compatible changes)
* `swiftide-indexing`: 0.14.4 -> 0.15.0
* `swiftide-query`: 0.14.4 -> 0.15.0 (✓ API compatible changes)
```
--- failure module_missing: pub module removed or renamed ---
Description:
A publicly-visible module cannot be imported by its prior path. A `pub use` may have been removed, or the module may have been renamed, removed, or made non-public.
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.38.0/src/lints/module_mi …
```

chore: release v0.15.0

---

swiftide-core/src/document.rs
swiftide-core/src/lib.rs
swiftide-core/src/metadata.rs
swiftide-core/src/query.rs
swiftide-integrations/src/lancedb/mod.rs
swiftide-integrations/src/lancedb/retrieve.rs
swiftide-integrations/src/pgvector/mod.rs
swiftide-integrations/src/pgvector/persist.rs
swiftide-integrations/src/pgvector/retrieve.rs
swiftide-integrations/src/qdrant/retrieve.rs
swiftide-query/src/answers/simple.rs
swiftide-query/src/evaluators/ragas.rs
swiftide-query/src/response_transformers/summary.rs
swiftide/tests/lancedb.rs
swiftide/tests/pgvector.rs

For simple RAG, just adding the content of a retrieved document might be enough. However, in more complex use cases, you might want to add metadata as well, as is or for conditional formatting.
For instance, when dealing with large amounts of chunked code, providing the path goes a long way. If generated metadata is good enough, could be useful as well.
With this retrieved Documents are treated as first class citizens. Additionally, this also paves the way for multi retrieval (and multi modal).
Documents can be formatted with `tera` in the answering step.

feat: Documents as first class citizens

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.15.0 -> 0.16.0 (✓ API compatible changes)
* `swiftide-agents`: 0.15.0 -> 0.16.0 (✓ API compatible changes)
* `swiftide-core`: 0.15.0 -> 0.16.0 (⚠️ API breaking changes)
* `swiftide-macros`: 0.15.0 -> 0.16.0
* `swiftide-integrations`: 0.15.0 -> 0.16.0 (✓ API compatible changes)
* `swiftide-indexing`: 0.15.0 -> 0.16.0 (✓ API compatible changes)
* `swiftide-query`: 0.15.0 -> 0.16.0 (✓ API compatible changes)
```
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.38.0/s …
```

chore: release v0.16.0

---

swiftide-core/src/chat_completion/traits.rs
swiftide-core/src/prompt.rs

Fixes an issue if strings suddenly include jinja style values by mistake. Bonus performance boost.

fix(prompts): Skip rendering prompts if no context and forward as is

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.16.0 -> 0.16.1 (✓ API compatible changes)
* `swiftide-agents`: 0.16.0 -> 0.16.1
* `swiftide-core`: 0.16.0 -> 0.16.1 (✓ API compatible changes)
* `swiftide-macros`: 0.16.0 -> 0.16.1
* `swiftide-indexing`: 0.16.0 -> 0.16.1
* `swiftide-integrations`: 0.16.0 -> 0.16.1 (✓ API compatible changes)
* `swiftide-query`: 0.16.0 -> 0.16.1
<blockquote>
- [d198bb0](https://github.com/bosun-ai/swiftide/commit/d198bb0807f5d5b12a51bc76721cc945be8e65b9) *(prompts)*  Skip rendering prompts if no context and forward as is (#530)
````text
Fixes an issue if strings suddenly include jinja style values by
mistake. Bonus performance boost.
````
- [4e8d59f](https://github.com/bosun-ai/swiftide/commit/4e8d59fbc0fbe72dd0f8d6a95e6e335280eb88e3) …

chore: release v0.16.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.16.1 -> 0.16.2 (✓ API compatible changes)
* `swiftide-agents`: 0.16.1 -> 0.16.2
* `swiftide-core`: 0.16.1 -> 0.16.2
* `swiftide-macros`: 0.16.1 -> 0.16.2
* `swiftide-indexing`: 0.16.1 -> 0.16.2
* `swiftide-integrations`: 0.16.1 -> 0.16.2
* `swiftide-query`: 0.16.1 -> 0.16.2
<blockquote>
- [2226755](https://github.com/bosun-ai/swiftide/commit/2226755f367d9006870a2dea2063655a7901d427)  Explicit cast on tools to Box<dyn> to make analyzer happy (#536)
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.16.1...0.16.2
</blockquote>
</p></details>
---

chore: release v0.16.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.16.3 -> 0.16.4 (✓ API compatible changes)
* `swiftide-agents`: 0.16.3 -> 0.16.4 (✓ API compatible changes)
* `swiftide-core`: 0.16.3 -> 0.16.4 (✓ API compatible changes)
* `swiftide-macros`: 0.16.3 -> 0.16.4
* `swiftide-indexing`: 0.16.3 -> 0.16.4 (✓ API compatible changes)
* `swiftide-integrations`: 0.16.3 -> 0.16.4 (✓ API compatible changes)
* `swiftide-query`: 0.16.3 -> 0.16.4 (✓ API compatible changes)
<blockquote>
- [c919484](https://github.com/bosun-ai/swiftide/commit/c9194845faa12b8a0fcecdd65f8ec9d3d221ba08)  Ollama via async-openai with chatcompletion support (#545)
````text
Adds support for chatcompletions (agents) for ollama. SimplePrompt and embeddings now use async-openai underneath.
Copy pasted as I expect …
```

chore: release v0.16.4

---

Cargo.lock
Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-integrations/src/treesitter/code_tree.rs
swiftide-integrations/src/treesitter/outliner.rs
swiftide-integrations/src/treesitter/queries.rs
swiftide-integrations/src/treesitter/supported_languages.rs

Seems someone conveniently forgot to add Golang support for the splitter (me). Implemented for splitter and refs/defs tools, not for outline yet.

feat(tree-sitter): Add golang support

---

Cargo.lock
swiftide-core/src/search_strategies/custom_strategy.rs
swiftide-integrations/src/lancedb/retrieve.rs
swiftide-integrations/src/pgvector/retrieve.rs
swiftide/Cargo.toml
swiftide/tests/lancedb.rs

Fixes: #511
This PR implements the `CustomStrategy<Q>` trait for LanceDB, enabling flexible and customizable vector similarity search capabilities. The implementation follows the successful pattern established in the pgvector integration while leveraging LanceDB-specific features.

feat(query): Add custom lancedb query generation for lancedb search

---

swiftide-agents/src/default_context.rs
swiftide-core/src/agent_traits.rs

Sometimes LLMs fail a completion without deterministic errors, or the user case where you just want to retry. `redrive` can now be called on a context, popping any new messages (if any), and making the messages available again to the agent.

feat(agents): Redrive completions manually on failure

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.16.4 -> 0.17.0 (✓ API compatible changes)
* `swiftide-agents`: 0.16.4 -> 0.17.0 (✓ API compatible changes)
* `swiftide-core`: 0.16.4 -> 0.17.0 (⚠️ API breaking changes)
* `swiftide-macros`: 0.16.4 -> 0.17.0
* `swiftide-indexing`: 0.16.4 -> 0.17.0
* `swiftide-integrations`: 0.16.4 -> 0.17.0 (✓ API compatible changes)
* `swiftide-query`: 0.16.4 -> 0.17.0
```
--- failure trait_method_added: pub trait method added ---
Description:
A non-sealed public trait added a new method without a default implementation, which breaks downstream implementations of the trait
ref: https://doc.rust-lang.org/cargo/reference/semver.html#trait-new-item-no-default
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.38.0/src/lints/trait_method_added.ron
Failed in:
trait method …
```

chore: release v0.17.0

---

swiftide-integrations/src/openai/chat_completion.rs

Ensures openai sticks much better to the schema and avoids accidental
mistakes.

fix(openai): Enable strict mode for tool calls

---

swiftide-agents/src/agent.rs
swiftide-agents/src/tools/arg_preprocessor.rs
swiftide-agents/src/tools/mod.rs

OpenAI has a tendency to sometimes send double keys. With this, Swiftide will now take the first key and ignore any after that.

feat(agents): Preprocess tool calls to fix common, fixable errors

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.17.0 -> 0.17.1 (✓ API compatible changes)
* `swiftide-agents`: 0.17.0 -> 0.17.1 (✓ API compatible changes)
* `swiftide-core`: 0.17.0 -> 0.17.1 (✓ API compatible changes)
* `swiftide-macros`: 0.17.0 -> 0.17.1
* `swiftide-indexing`: 0.17.0 -> 0.17.1
* `swiftide-integrations`: 0.17.0 -> 0.17.1 (✓ API compatible changes)
* `swiftide-query`: 0.17.0 -> 0.17.1
<blockquote>
- [e4e4468](https://github.com/bosun-ai/swiftide/commit/e4e44681b65b07b5f1e987ce468bdcda61eb30da) *(agents)*  Implement AgentContext for smart dyn pointers
- [70181d9](https://github.com/bosun-ai/swiftide/commit/70181d9642aa2c0a351b9f42be1a8cdbd83c9075) *(agents)*  Add pub accessor for agent context (#558)
- …

chore: release v0.17.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.17.1 -> 0.17.2 (✓ API compatible changes)
* `swiftide-agents`: 0.17.1 -> 0.17.2 (✓ API compatible changes)
* `swiftide-core`: 0.17.1 -> 0.17.2
* `swiftide-macros`: 0.17.1 -> 0.17.2
* `swiftide-indexing`: 0.17.1 -> 0.17.2
* `swiftide-integrations`: 0.17.1 -> 0.17.2
* `swiftide-query`: 0.17.1 -> 0.17.2
<blockquote>
- [47db5ab](https://github.com/bosun-ai/swiftide/commit/47db5ab138384a6c235a90024470e9ab96751cc8) *(agents)*  Redrive uses the correct pointer and works as intended
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.17.1...0.17.2
</blockquote>
</p></details>
---

chore: release v0.17.2

---

swiftide-agents/src/agent.rs
swiftide-indexing/src/pipeline.rs
swiftide-query/src/query/pipeline.rs

When a span is emitted that would be selected by the subscriber, but we instrument its closure with a span that would not be selected by the subscriber, the span would be emitted as an orphan (with a new `trace_id`) making them hard to find and cluttering dashboards.
This situation is also documented here: https://docs.rs/tracing/latest/tracing/struct.Span.html#method.or_current

fix(tracing): Use `or_current()` to prevent orphaned tracing spans

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.17.3 -> 0.17.4 (✓ API compatible changes)
* `swiftide-agents`: 0.17.3 -> 0.17.4 (✓ API compatible changes)
* `swiftide-core`: 0.17.3 -> 0.17.4
* `swiftide-macros`: 0.17.3 -> 0.17.4
* `swiftide-indexing`: 0.17.3 -> 0.17.4 (✓ API compatible changes)
* `swiftide-integrations`: 0.17.3 -> 0.17.4
* `swiftide-query`: 0.17.3 -> 0.17.4 (✓ API compatible changes)
<blockquote>
- [0d9e250](https://github.com/bosun-ai/swiftide/commit/0d9e250e2512fe9c66d5dfd2ac688dcd56bd07e9) *(tracing)*  Use `or_current()` to prevent orphaned tracing spans (#573)
````text
When a span is emitted that would be selected by the subscriber, but we
instrument its closure with a span that would not be selected by the
subscriber, the span would be emitted …
```

chore: release v0.17.4

---

swiftide-agents/src/agent.rs
swiftide-agents/src/hooks.rs
swiftide-agents/src/test_utils.rs

Enables a lot more customizability than yielding just the agent. The
context can still be accessed through agent#context.

feat(agents)!: Yield agent in hooks instead of context

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.17.5 -> 0.18.0 (✓ API compatible changes)
* `swiftide-agents`: 0.17.5 -> 0.18.0 (⚠️ API breaking changes)
* `swiftide-core`: 0.17.5 -> 0.18.0 (✓ API compatible changes)
* `swiftide-macros`: 0.17.5 -> 0.18.0
* `swiftide-indexing`: 0.17.5 -> 0.18.0 (✓ API compatible changes)
* `swiftide-integrations`: 0.17.5 -> 0.18.0 (✓ API compatible changes)
* `swiftide-query`: 0.17.5 -> 0.18.0 (✓ API compatible changes)
```
--- failure enum_variant_added: enum variant added on exhaustive enum ---
Description:
A publicly-visible enum without #[non_exhaustive] has a new variant.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.38.0/src/lints/enum_variant_added.ron
Failed in:
variant HookTypes:OnStart …
```

chore: release v0.18.0

---

Cargo.lock
deny.toml
swiftide-integrations/src/openai/chat_completion.rs
swiftide-integrations/src/openai/embed.rs
swiftide-integrations/src/openai/mod.rs
swiftide-integrations/src/openai/simple_prompt.rs
swiftide/src/lib.rs
swiftide/tests/dyn_traits.rs

async-openai already supports connecting with the azure api, the only change necessary was adding generics.
This is technically a breaking change, however I've make the regular openai config the default limiting the downstream need for changes.

feat: add generics to allow azure integration

---

Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-integrations/src/treesitter/code_tree.rs
swiftide-integrations/src/treesitter/outliner.rs
swiftide-integrations/src/treesitter/queries.rs
swiftide-integrations/src/treesitter/supported_languages.rs

This pr adds solidity support. 
Notes:
* I've added queries, but have omitted outlining for now.
* The simple testcase should ensure the queries are correct ( I copied them from upstream anyways 🤷‍♂️ )
I had a quick question while writing this pr, is there any reason why the tags.scm file packaged with the parsers isn't used? or was this just easier for now.

feat: add solidity support

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.18.1 -> 0.18.2 (✓ API compatible changes)
* `swiftide-agents`: 0.18.1 -> 0.18.2
* `swiftide-core`: 0.18.1 -> 0.18.2
* `swiftide-macros`: 0.18.1 -> 0.18.2
* `swiftide-indexing`: 0.18.1 -> 0.18.2
* `swiftide-integrations`: 0.18.1 -> 0.18.2 (✓ API compatible changes)
* `swiftide-query`: 0.18.1 -> 0.18.2
<blockquote>
- [50ffa15](https://github.com/bosun-ai/swiftide/commit/50ffa156e28bb085a61a376bab71c135bc09622f)  Anthropic support for prompts and agents (#602)
- [8cf70e0](https://github.com/bosun-ai/swiftide/commit/8cf70e08787d1376ba20001cc9346767d8bd84ef) *(integrations)*  Ensure anthropic tool call format is consistent with specs
- [98176c6](https://github.com/bosun-ai/swiftide/commit/98176c603b61e3971ca5583f9f4346eb5b96 …

chore: release v0.18.2

---

swiftide-agents/src/agent.rs
swiftide-agents/src/test_utils.rs
swiftide-core/src/chat_completion/errors.rs
swiftide-core/src/chat_completion/tools.rs

Specifically meant for LLMs sending invalid JSON, these tool calls are now retried by feeding back the error into the LLM up to a limit (default 3).

feat(agents): By default retry failed tools with LLM up to 3 times

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.18.2 -> 0.19.0 (✓ API compatible changes)
* `swiftide-agents`: 0.18.2 -> 0.19.0 (✓ API compatible changes)
* `swiftide-core`: 0.18.2 -> 0.19.0 (✓ API compatible changes)
* `swiftide-macros`: 0.18.2 -> 0.19.0
* `swiftide-indexing`: 0.18.2 -> 0.19.0 (✓ API compatible changes)
* `swiftide-integrations`: 0.18.2 -> 0.19.0 (⚠ API breaking changes)
* `swiftide-query`: 0.18.2 -> 0.19.0
```text
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.39.0/src/lints/cons …
```

chore: release v0.19.0

---

Cargo.toml
examples/hello_agents.rs
swiftide-core/src/chat_completion/tools.rs
swiftide-integrations/src/anthropic/chat_completion.rs
swiftide-integrations/src/ollama/chat_completion.rs
swiftide-integrations/src/open_router/chat_completion.rs
swiftide-integrations/src/openai/chat_completion.rs
swiftide-macros/Cargo.toml
swiftide-macros/src/tool/args.rs
swiftide-macros/src/tool/mod.rs
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_lifetime.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_multiple_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg.snap
swiftide-macros/src/tool/tool_spec.rs
swiftide-macros/tests/tool/tool_missing_arg_fail.rs
swiftide-macros/tests/tool/tool_missing_arg_fail.stderr
swiftide-macros/tests/tool/tool_missing_parameter_fail.stderr
swiftide-macros/tests/tool/tool_single_argument_pass.rs

Add support for numbers, arrays and boolean types in the `#[swiftide_macros::tool]` attribute macro. For enum and object a custom implementation is now properly supported as well, but not via the macro. For now, tools using Derive also still need a custom implementation.

feat(agents): Add support for numbers, arrays and booleans in tool args

---

Cargo.lock
Cargo.toml

chore: update to async-anthropic 0.3.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide`: 0.20.0 -> 0.20.1 (✓ API compatible changes)
* `swiftide-agents`: 0.20.0 -> 0.20.1
* `swiftide-core`: 0.20.0 -> 0.20.1
* `swiftide-macros`: 0.20.0 -> 0.20.1
* `swiftide-indexing`: 0.20.0 -> 0.20.1 (✓ API compatible changes)
* `swiftide-integrations`: 0.20.0 -> 0.20.1
* `swiftide-query`: 0.20.0 -> 0.20.1
<blockquote>
- [0aa1248](https://github.com/bosun-ai/swiftide/commit/0aa124819d836f37d1fcaf88e6f88b5affb46cf9) *(indexing)*  Handle invalid utf-8 in fileloader lossy (#632)
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.20.0...0.20.1
</blockquote>
</p></details>
---

chore: release v0.20.1

---

swiftide-agents/src/agent.rs
swiftide-agents/src/test_utils.rs
swiftide-agents/src/tools/control.rs
swiftide-core/src/chat_completion/tools.rs
swiftide-core/src/chat_completion/traits.rs
swiftide-integrations/src/anthropic/chat_completion.rs
swiftide-integrations/src/ollama/chat_completion.rs
swiftide-integrations/src/open_router/chat_completion.rs
swiftide-integrations/src/openai/chat_completion.rs
swiftide-macros/src/tool/mod.rs
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_lifetime.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_multiple_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg.snap

Previously ToolSpec and name in the `Tool` trait worked with static. With these changes, there is a lot more flexibility, allowing for i.e. run-time tool generation.

feat(agents): Improve flexibility for tool generation

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide`: 0.20.1 -> 0.21.0 (✓ API compatible changes)
* `swiftide-agents`: 0.20.1 -> 0.21.0 (✓ API compatible changes)
* `swiftide-core`: 0.20.1 -> 0.21.0 (⚠ API breaking changes)
* `swiftide-macros`: 0.20.1 -> 0.21.0
* `swiftide-indexing`: 0.20.1 -> 0.21.0
* `swiftide-integrations`: 0.20.1 -> 0.21.0 (✓ API compatible changes)
* `swiftide-query`: 0.20.1 -> 0.21.0
```text
--- failure method_requires_different_generic_type_params: method now requires a different number of generic type parameters ---
Description:
A method now requires a different number of generic type parameters than it used to. Uses of this method that supplied the previous number of generic types will be broken.
ref: https://doc.rust-lang.org/reference/items/generics.html
impl: …
```

chore: release v0.21.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.21.0 -> 0.21.1 (✓ API compatible changes)
* `swiftide-macros`: 0.21.0 -> 0.21.1
* `swiftide-agents`: 0.21.0 -> 0.21.1
* `swiftide-indexing`: 0.21.0 -> 0.21.1
* `swiftide-integrations`: 0.21.0 -> 0.21.1 (✓ API compatible changes)
* `swiftide-query`: 0.21.0 -> 0.21.1
* `swiftide`: 0.21.0 -> 0.21.1 (✓ API compatible changes)
<blockquote>
- [f418c5e](https://github.com/bosun-ai/swiftide/commit/f418c5ee2f0d3ee87fb3715ec6b1d7ecc80bf714) *(ci)*  Run just a single real rerank test to please the flaky gods
- [e387e82](https://github.com/bosun-ai/swiftide/commit/e387e826200e1bc0a608e1f680537751cfc17969) *(lancedb)*  Update Lancedb to 0.17 and pin Arrow to a lower version
- …

chore: release v0.21.1

---

swiftide-agents/src/agent.rs

Continues the agent on tool failure, related to https://github.com/bosun-ai/kwaak/issues/313

feat: Continue Agent on Tool Failure

---

swiftide-indexing/src/loaders/file_loader.rs

Allows playing with the iterator outside of the stream.
Relates to https://github.com/bosun-ai/kwaak/issues/337

feat(indexing): Add `iter()` for file loader

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide-core`: 0.21.1 -> 0.22.0 (✓ API compatible changes)
* `swiftide-macros`: 0.21.1 -> 0.22.0
* `swiftide-agents`: 0.21.1 -> 0.22.0 (✓ API compatible changes)
* `swiftide-indexing`: 0.21.1 -> 0.22.0 (✓ API compatible changes)
* `swiftide-integrations`: 0.21.1 -> 0.22.0 (⚠ API breaking changes)
* `swiftide-query`: 0.21.1 -> 0.22.0 (✓ API compatible changes)
* `swiftide`: 0.21.1 -> 0.22.0 (✓ API compatible changes)
```text
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.39. …
```

chore: release v0.22.0

---

swiftide-integrations/src/openai/chat_completion.rs
swiftide-integrations/src/openai/mod.rs

o3-mini needs to omit parallel_tool_calls - so we need to allow for a None option to not include that field 
needed for https://github.com/bosun-ai/kwaak/pull/392

fix(integrations): Make openai parallel_tool_calls an Option

---

Cargo.lock
Cargo.toml
swiftide-core/src/indexing_stream.rs
swiftide-core/src/search_strategies/custom_strategy.rs
swiftide-core/src/template.rs
swiftide-integrations/Cargo.toml
swiftide-integrations/src/duckdb/mod.rs
swiftide-integrations/src/duckdb/node_cache.rs
swiftide-integrations/src/duckdb/persist.rs
swiftide-integrations/src/duckdb/retrieve.rs
swiftide-integrations/src/duckdb/schema.sql
swiftide-integrations/src/duckdb/upsert.sql
swiftide-integrations/src/lib.rs
swiftide/Cargo.toml

Adds support for Duckdb. Persist, Retrieve (Simple and Custom), and NodeCache are implemented.

feat: Duckdb

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
* `swiftide-agents`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
* `swiftide-macros`: 0.22.0 -> 0.22.1
* `swiftide-indexing`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
* `swiftide-integrations`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
* `swiftide-query`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
* `swiftide`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
<blockquote>
- [474d612](https://github.com/bosun-ai/swiftide/commit/474d6122596e71132e35fcb181302dfed7794561) *(integrations)*  Add Duckdb support ([#578](https://github.com/bosun-ai/swiftide/pull/578))
````text
Adds support for Duckdb. Persist, Retrieve (Simple and Custom), and
NodeCache are implemented.
````
- …

chore: release v0.22.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.22.2 -> 0.22.3
* `swiftide-agents`: 0.22.2 -> 0.22.3
* `swiftide-macros`: 0.22.2 -> 0.22.3
* `swiftide-indexing`: 0.22.2 -> 0.22.3
* `swiftide-integrations`: 0.22.2 -> 0.22.3 (✓ API compatible changes)
* `swiftide-query`: 0.22.2 -> 0.22.3
* `swiftide`: 0.22.2 -> 0.22.3 (✓ API compatible changes)
<blockquote>
- [834fcd3](https://github.com/bosun-ai/swiftide/commit/834fcd3b2270904bcfe8998a7015de15626128a8)  Update duckdb to 1.2.1 ([#680](https://github.com/bosun-ai/swiftide/pull/680))
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.22.2...0.22.3
</blockquote>
</p></details>
---

chore: release v0.22.3

---

swiftide-agents/Cargo.toml
swiftide-agents/src/lib.rs
swiftide-core/Cargo.toml
swiftide-core/src/lib.rs
swiftide-indexing/Cargo.toml
swiftide-indexing/src/lib.rs
swiftide-integrations/Cargo.toml
swiftide-integrations/src/lib.rs
swiftide-macros/Cargo.toml
swiftide-macros/src/lib.rs
swiftide-query/Cargo.toml
swiftide-query/src/lib.rs
swiftide-test-utils/Cargo.toml
swiftide-test-utils/src/lib.rs
swiftide/src/lib.rs

https://doc.rust-lang.org/rustdoc/unstable-features.html#extensions-to-the-doc-attribute
This is an unstable feature, so it's feature flagged with a feature that
is always passed by docs.rs. To run the same settings use cargo-docs-rs
Also moves the logo into the top left corner of all docs, rather than
just in the main doc.
Makes the docs.rs config consistent across all crate manifests.

docs: document feature flags using doc_auto_cfg

---

swiftide-integrations/Cargo.toml

The Qdrant integration calls chrono::Utc::now(), which requires the now feature flag to be enabled in the chrono crate when using qdrant
https://github.com/bosun-ai/swiftide/blob/5f2a5e29b8ba98ddf4fc44f20c1e8da3f25229fa/swiftide-integrations/src/qdrant/indexing_node.rs#L57

fix(integrations): Add chrono/utc feature flag when using qdrant

---

.github/workflows/lint.yml

Disabling default features in deps lead to some feature flags not compiling correctly on their own. Added as a future safety guard. (#684)

chore(ci): Verify each feature compiles individually with cargo hack

---

Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-agents/src/tools/local_executor.rs
swiftide-indexing/Cargo.toml
swiftide-indexing/src/loaders/file_loader.rs
swiftide-integrations/Cargo.toml
swiftide-integrations/src/parquet/loader.rs

Uses fs-err crate to automatically include filenames in the error messages

chore: include filenames in errors in file io

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.22.3 -> 0.22.4 (✓ API compatible changes)
* `swiftide-agents`: 0.22.3 -> 0.22.4 (✓ API compatible changes)
* `swiftide-macros`: 0.22.3 -> 0.22.4
* `swiftide-indexing`: 0.22.3 -> 0.22.4 (✓ API compatible changes)
* `swiftide-integrations`: 0.22.3 -> 0.22.4 (✓ API compatible changes)
* `swiftide-query`: 0.22.3 -> 0.22.4 (✓ API compatible changes)
* `swiftide`: 0.22.3 -> 0.22.4 (✓ API compatible changes)
<blockquote>
- [4ec00bb](https://github.com/bosun-ai/swiftide/commit/4ec00bb0fed214f27629f32569406bfa2c786dd7) *(integrations)*  Add chrono/utc feature flag when using qdrant ([#684](https://github.com/bosun-ai/swiftide/pull/684))
````text
The Qdrant integration calls chrono::Utc::now(), which requires the now …
```

chore: release v0.22.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.22.4 -> 0.22.5 (✓ API compatible changes)
* `swiftide-agents`: 0.22.4 -> 0.22.5 (✓ API compatible changes)
* `swiftide-macros`: 0.22.4 -> 0.22.5
* `swiftide-indexing`: 0.22.4 -> 0.22.5 (✓ API compatible changes)
* `swiftide-integrations`: 0.22.4 -> 0.22.5 (✓ API compatible changes)
* `swiftide-query`: 0.22.4 -> 0.22.5
* `swiftide`: 0.22.4 -> 0.22.5 (✓ API compatible changes)
<blockquote>
- [eb4e044](https://github.com/bosun-ai/swiftide/commit/eb4e0442293e17722743aa2b88d8dd7582dd9236)  Estimate tokens for OpenAI like apis with tiktoken-rs ([#699](https://github.com/bosun-ai/swiftide/pull/699))
- [345c57a](https://github.com/bosun-ai/swiftide/commit/345c57a663dd0d315a28f0927c5d598ba21d019d)  Improve file loader …

chore: release v0.22.5

---

Cargo.toml
swiftide-integrations/src/duckdb/mod.rs
swiftide-integrations/src/duckdb/retrieve.rs

1.2.1 still has issues on Mac with the vss extension (seems discord
agrees). This loosens up the requirements so people can use the version
that works for them

fix(integrations): Loosen up duckdb requirements even more and make it more flexible for version requirements

---

examples/hello_agents.rs
swiftide-agents/src/agent.rs
swiftide-integrations/src/pgvector/fixtures.rs
swiftide-macros/src/lib.rs
swiftide-macros/src/tool/args.rs
swiftide-macros/src/tool/mod.rs
swiftide-macros/src/tool/rust_to_json_type.rs
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_option.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_multiple_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg_option.snap
swiftide-macros/src/tool/tool_spec.rs
swiftide-macros/tests/tool/tool_derive_pass.rs
swiftide-macros/tests/tool/tool_missing_arg_fail.rs
swiftide-macros/tests/tool/tool_missing_arg_fail.stderr
swiftide-macros/tests/tool/tool_missing_parameter_fail.stderr
swiftide-macros/tests/tool/tool_single_argument_pass.rs
swiftide/tests/indexing_pipeline.rs

Adds support for `Option` values in tool params. These are marked as not required in the generated json spec.
Reworked the tool macros so that the json_type is no longer required if its not a string, most of the time it can be inferred (at least on attribute macros).
You can now also overwrite the rust type, rename the tool (`name`) or rename the inner function the tool will call (`fn_name`).
This also opens the door for supporting enums, nested objects and other foo. Overall the code is also a lot cleaner, bonus.

feat(macros): Support optional values and make them even nicer to use

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.22.5 -> 0.22.6
* `swiftide-agents`: 0.22.5 -> 0.22.6 (✓ API compatible changes)
* `swiftide-macros`: 0.22.5 -> 0.22.6
* `swiftide-indexing`: 0.22.5 -> 0.22.6
* `swiftide-integrations`: 0.22.5 -> 0.22.6 (✓ API compatible changes)
* `swiftide-query`: 0.22.5 -> 0.22.6
* `swiftide`: 0.22.5 -> 0.22.6 (✓ API compatible changes)
<blockquote>
- [a05b3c8](https://github.com/bosun-ai/swiftide/commit/a05b3c8e7c4224c060215c34490b2ea7729592bf) *(macros)*  Support optional values and make them even nicer to use ([#703](https://github.com/bosun-ai/swiftide/pull/703))
- [1866d5a](https://github.com/bosun-ai/swiftide/commit/1866d5a081f40123e607208d04403fb98f34c057) *(integrations)*  Loosen up duckdb requirements even more and make …

chore: release v0.22.6

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.22.6 -> 0.22.7
* `swiftide-agents`: 0.22.6 -> 0.22.7
* `swiftide-macros`: 0.22.6 -> 0.22.7
* `swiftide-indexing`: 0.22.6 -> 0.22.7
* `swiftide-integrations`: 0.22.6 -> 0.22.7 (✓ API compatible changes)
* `swiftide-query`: 0.22.6 -> 0.22.7
* `swiftide`: 0.22.6 -> 0.22.7 (✓ API compatible changes)
<blockquote>
- [b0001fb](https://github.com/bosun-ai/swiftide/commit/b0001fbb12cf6bb85fc4d5a8ef0968219e8c78db) *(duckdb)*  Upsert is now opt in as it requires duckdb >= 1.2 ([#708](https://github.com/bosun-ai/swiftide/pull/708))
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.22.6...0.22.7
</blockquote>
</p></details>
---
This PR was generated with …

chore: release v0.22.7

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.22.7 -> 0.22.8
* `swiftide-agents`: 0.22.7 -> 0.22.8
* `swiftide-macros`: 0.22.7 -> 0.22.8
* `swiftide-indexing`: 0.22.7 -> 0.22.8
* `swiftide-integrations`: 0.22.7 -> 0.22.8
* `swiftide-query`: 0.22.7 -> 0.22.8
* `swiftide`: 0.22.7 -> 0.22.8 (✓ API compatible changes)
<blockquote>
- [6b4dfca](https://github.com/bosun-ai/swiftide/commit/6b4dfca822f39b3700d60e6ea31b9b48ccd6d56f)  Tool macros should work with latest darling version ([#712](https://github.com/bosun-ai/swiftide/pull/712))
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.22.7...0.22.8
</blockquote>
</p></details>
---

chore: release v0.22.8

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/agents_mcp_tools.rs
swiftide-agents/Cargo.toml
swiftide-agents/src/agent.rs
swiftide-agents/src/tools/mcp.rs
swiftide-agents/src/tools/mod.rs
swiftide-core/src/agent_traits.rs
swiftide-core/src/chat_completion/mod.rs
swiftide-core/src/chat_completion/tools.rs
swiftide-core/src/chat_completion/traits.rs
swiftide/Cargo.toml
swiftide/src/lib.rs

Adds support for agents to use tools from MCP servers. All transports are supported via the `rmcp` crate. 
Additionally adds the possibility to add toolboxes to agents (of which MCP is one). Tool boxes declare their available tools at runtime, like tool box.

feat: Agent mcp client support 

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide-core`: 0.22.8 -> 0.23.0 (⚠ API breaking changes)
* `swiftide-agents`: 0.22.8 -> 0.23.0 (⚠ API breaking changes)
* `swiftide-macros`: 0.22.8 -> 0.23.0
* `swiftide-indexing`: 0.22.8 -> 0.23.0 (✓ API compatible changes)
* `swiftide-integrations`: 0.22.8 -> 0.23.0 (✓ API compatible changes)
* `swiftide-query`: 0.22.8 -> 0.23.0 (✓ API compatible changes)
* `swiftide`: 0.22.8 -> 0.23.0 (✓ API compatible changes)
```text
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.40.0/ …
```

chore: release v0.23.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide-core`: 0.23.0 -> 0.24.0 (⚠ API breaking changes)
* `swiftide-agents`: 0.23.0 -> 0.24.0 (✓ API compatible changes)
* `swiftide-macros`: 0.23.0 -> 0.24.0
* `swiftide-indexing`: 0.23.0 -> 0.24.0 (✓ API compatible changes)
* `swiftide-integrations`: 0.23.0 -> 0.24.0 (✓ API compatible changes)
* `swiftide-query`: 0.23.0 -> 0.24.0
* `swiftide`: 0.23.0 -> 0.24.0 (✓ API compatible changes)
```text
--- failure enum_missing: pub enum removed or renamed ---
Description:
A publicly-visible enum cannot be imported by its prior path. A `pub use` may have been removed, or the enum itself may have been renamed or removed entirely.
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.40.0/src/lints/enum_missing.ro …
```

chore: release v0.24.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide-core`: 0.24.0 -> 0.25.0 (⚠ API breaking changes)
* `swiftide-agents`: 0.24.0 -> 0.25.0 (⚠ API breaking changes)
* `swiftide-macros`: 0.24.0 -> 0.25.0
* `swiftide-indexing`: 0.24.0 -> 0.25.0 (✓ API compatible changes)
* `swiftide-integrations`: 0.24.0 -> 0.25.0 (✓ API compatible changes)
* `swiftide-query`: 0.24.0 -> 0.25.0 (✓ API compatible changes)
* `swiftide`: 0.24.0 -> 0.25.0 (✓ API compatible changes)
```text
--- failure enum_discriminants_undefined_non_unit_variant: enum's variants no longer have defined discriminants due to non-unit variant ---
Description:
An enum's variants no longer have well-defined discriminant values due to a tuple or struct variant in the enum. This breaks downstream code that accesses discriminants via a numeric cast like `as isize`.
ref: …
```

chore: release v0.25.0

---

swiftide-indexing/src/pipeline.rs

Makes logging in the indexing pipeline consistent. All steps and logs are now at trace level.
Part of #686

chore: Consistent logging for indexing pipeline

---

examples/Cargo.toml
examples/agents_with_human_in_the_loop.rs
swiftide-agents/src/agent.rs
swiftide-agents/src/default_context.rs
swiftide-agents/src/lib.rs
swiftide-agents/src/state.rs
swiftide-agents/src/test_utils.rs
swiftide-agents/src/tools/arg_preprocessor.rs
swiftide-agents/src/tools/control.rs
swiftide-agents/src/tools/mcp.rs
swiftide-core/src/agent_traits.rs
swiftide-core/src/chat_completion/tools.rs
swiftide-core/src/chat_completion/traits.rs
swiftide-integrations/src/anthropic/chat_completion.rs
swiftide-macros/src/tool/mod.rs
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_generics.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_lifetime.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_derive_with_option.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_multiple_args.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg.snap
swiftide-macros/src/tool/snapshots/swiftide_macros__tool__tests__snapshot_single_arg_option.snap

Tools can now return a FeedbackRequired with an optional Value payload. The agent will stop, with the tool call and optional payload in the reason. Possible to use either the stop reason returned by the agent or a hook to act on this, or use it in your own tools.
Feedback is given on the context of the agent with the tool call and an optional payload. The payload offers flexibility to provide feedback to the tool, or to provide context to the user.
BREAKING CHANGE: The `Tool` trait now receives a `ToolCall` as argument instead of an `Option<&str>`. The latter is still accessible via `tool_call.args()`.

feat(agents)!: Easy human-in-the-loop flows by decorating tools

---

README.md
examples/hello_agents.rs
swiftide-agents/src/default_context.rs
swiftide-core/src/agent_traits.rs

Current solution leaks information of the executor through the context.
Instead, access the executor directly. This also offers more flexibility
to do more creative stuff in tools and elsewhere.

refactor(agents): Direct access to executor via context

---

swiftide-agents/src/default_context.rs
swiftide-core/src/agent_traits.rs
swiftide-integrations/src/redis/message_history.rs
swiftide-integrations/src/redis/mod.rs

- **feat(agents)!: Context is now generic over its backend**
- **fix(openai): Opt-out streaming accumulated response and only get the delta (#809)**
- **chore(deps): bump the minor group across 1 directory with 3 updates (#806)**
- **feat(redis): Add support for Redis based agent message history**

feat(redis): Support `MessageHistory` for redis

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-macros/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide-core`: 0.26.0 -> 0.27.0 (⚠ API breaking changes)
* `swiftide-agents`: 0.26.0 -> 0.27.0 (⚠ API breaking changes)
* `swiftide-macros`: 0.26.0 -> 0.27.0
* `swiftide-indexing`: 0.26.0 -> 0.27.0 (✓ API compatible changes)
* `swiftide-integrations`: 0.26.0 -> 0.27.0 (⚠ API breaking changes)
* `swiftide-query`: 0.26.0 -> 0.27.0 (✓ API compatible changes)
* `swiftide`: 0.26.0 -> 0.27.0 (✓ API compatible changes)
```text
--- failure trait_method_added: pub trait method added ---
Description:
A non-sealed public trait added a new method without a default implementation, which breaks downstream implementations of the trait
ref: https://doc.rust-lang.org/cargo/reference/semver.html#trait-new-item-no-default
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/trai …
```

chore: release v0.27.0

---

swiftide-core/Cargo.toml
swiftide-core/src/chat_completion/traits.rs
swiftide-core/src/indexing_decorators.rs
swiftide-core/src/lib.rs
swiftide-core/src/stream_backoff.rs
swiftide-integrations/src/openai/mod.rs

- **fix(openai): More gracefully allow handling streaming errors if the client is decorated**
- **feat: Proper streaming backoff for ChatCompletion**

feat: Proper streaming backoff for Chat Completion

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-agents/Cargo.toml
swiftide-indexing/Cargo.toml
swiftide-integrations/Cargo.toml
swiftide-query/Cargo.toml
swiftide/Cargo.toml

* `swiftide-core`: 0.30.1 -> 0.31.0 (⚠ API breaking changes)
* `swiftide-macros`: 0.30.1 -> 0.31.0
* `swiftide-indexing`: 0.30.1 -> 0.31.0 (⚠ API breaking changes)
* `swiftide-agents`: 0.30.1 -> 0.31.0 (⚠ API breaking changes)
* `swiftide-integrations`: 0.30.1 -> 0.31.0 (✓ API compatible changes)
* `swiftide-langfuse`: 0.30.1 -> 0.31.0 (✓ API compatible changes)
* `swiftide-query`: 0.30.1 -> 0.31.0 (✓ API compatible changes)
* `swiftide`: 0.30.1 -> 0.31.0 (⚠ API breaking changes)
```text
--- failure method_requires_different_generic_type_params: method now requires a different number of generic type parameters ---
Description:
A method now requires a different number of generic type parameters than it used to. Uses of this method that supplied the previous number of generic types will be …
```

chore: release v0.31.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
swiftide-query/Cargo.toml

* `swiftide-core`: 0.31.2 -> 0.31.3 (✓ API compatible changes)
* `swiftide-macros`: 0.31.2 -> 0.31.3
* `swiftide-indexing`: 0.31.2 -> 0.31.3
* `swiftide-agents`: 0.31.2 -> 0.31.3
* `swiftide-integrations`: 0.31.2 -> 0.31.3 (✓ API compatible changes)
* `swiftide-langfuse`: 0.31.2 -> 0.31.3
* `swiftide-query`: 0.31.2 -> 0.31.3
* `swiftide`: 0.31.2 -> 0.31.3 (✓ API compatible changes)
<blockquote>
- [a189ae6](https://github.com/bosun-ai/swiftide/commit/a189ae6de51571810f98cf58f9fdb58e7707f29a) *(integrations/openai)*  Opt-in responses api ([#943](https://github.com/bosun-ai/swiftide/pull/943))
**Full Changelog**: https://github.com/bosun-ai/swiftide/compare/0.31.2...0.31.3
</blockquote>
</p></details>
---
This PR was generated with …

chore: release v0.31.3
